### ISSUE TITLE
ASI loader unable to load the fix

### ISSUE THREAD

**Issue by Dat1ScrubLord** [nuggslet/MGSM2Fix#10]
I'm not sure if I've done anything wrong, this issue randomly popped up after a few days without any issues, it every single time I try to load MGS I get the error "Unable to load MGSM2Fix.asi. Error: 225"

**Comment by nuggslet** [comment]
From a quick Google, looks like this might be related to issue #9. Hopefully sorts itself out in the next release, will see about shuffling things around to try and help solve it.

**Comment by nuggslet** [comment]
Hopefully fixed since v0.7? Feel free to reopen if not.
