### ISSUE TITLE
The new 1.4.0 update adds new screen and visual options for MGS1, so when the mod is installed those specific options do not work in the game.

### ISSUE THREAD

**Issue by Solopoio** [nuggslet/MGSM2Fix#11]
You only can change the setting via mod files, the ingame options will do nothing.

![image](https://github.com/nuggslet/MGSM2Fix/assets/154438031/c2039a0b-c66b-4036-a6d5-abe1393b1f83)

All the other things of the mod like custom resolution seem to work as before the 1.4.0 update.

**Comment by nuggslet** [comment]
Fixed.
