### ISSUE TITLE
Analog movement?

### ISSUE THREAD

**Issue by Noname00000001** [nuggslet/MGSM2Fix#2]
Hey

I know this ain't a issue with the mod, so I hope it is alright I ask here anyway :)

Not sure what is possible or even in the scope of this mod, but would analog movement be something that could be enabled for MGS via this mod?

Anywho, great work so far with what you have done! It's nice to have a simple and easy mothed to change the settings you have made, instead of the others where you need to patch with .bat files and whatnot.

**Comment by KoKlusz** [comment]
The game supports analog movement, it's just not enabled in the emulator. So it's most probably doable. (not that I have any idea how to do it, lol)

A better question is, can anything be done regarding input lag?
