### ISSUE TITLE
[Bug]: Screen Is Aligned to the Top

### ISSUE THREAD

**Issue by LethalPlacebo** [nuggslet/MGSM2Fix#21]
## Log Files:
[MGSM2Fix.log](https://github.com/nuggslet/MGSM2Fix/files/14188532/MGSM2Fix.log)

## Reproduction: My settings are set to borderless mode and increased internal resolution is on, however widescreen is OFF.
![20240206185425_1](https://github.com/nuggslet/MGSM2Fix/assets/27256322/38fd90f1-5665-49c8-a95a-add6882a3faa)

**Comment by ShizCalev** [comment]
Log dive - playing Integral

![image](https://github.com/nuggslet/MGSM2Fix/assets/6209658/6c8e237f-ca45-45ef-b0cb-81e2586bf285)
Known Issue

**Comment by LethalPlacebo** [comment]
Ahh, interesting. I'm the playing the US version here, but because Integral has that quirk it treats them all the same, huh? Weird. Also when I uninstall MGSM2Fix, the game is aligned correctly for me, whether I use the Standard or Pixel Perfect aspect ratios. The pic shown below is without the fix installed, on the US version.
![20240206205036_1](https://github.com/nuggslet/MGSM2Fix/assets/27256322/40a23b1f-e62a-41e2-955c-067a642e4410)

**Comment by nuggslet** [comment]
I have a fix for this that should be in the next release.

**Comment by LethalPlacebo** [comment]
> I have a fix for this that should be in the next release.

Glad to hear it!

**Comment by nuggslet** [comment]
Should be sorted https://github.com/nuggslet/MGSM2Fix/releases/tag/v2.2.

**Comment by LunaRosalie** [comment]
Just want to say that i still have this problem on 2.2 but only when i use the enhance internal resolution

**Comment by LethalPlacebo** [comment]
> Just want to say that i still have this problem on 2.2 but only when i use the enhance internal resolution

That's strange, on 2.2 I am able to enhance the internal resolution and the screen is still properly aligned. I am playing the North American version.

**Comment by LunaRosalie** [comment]
i reinstalled the game and mod from scratch and now i have black bars unlike PAL version but its way better than top alligned i had before 
![Screenshot_2](https://github.com/nuggslet/MGSM2Fix/assets/109091642/5b759cbb-aa5a-45c0-8b4d-e3d40f1ccb29)
