### ISSUE TITLE
[Bug]: Cannot see codec frequency

### ISSUE THREAD

**Issue by Maxilos9999** [nuggslet/MGSM2Fix#27]
The codec frequency is invisible when this is installed, leading to not being able to save.

**Comment by philipmodig** [comment]
I also have this problem, I can't see the codec numbers and I can't see the name of my saves but I can still save.

Workaround: Press down and you can find mei ling codec and save.
For others codec you have to start at a close frequency, and then count every press.

Some examples:
For Meryl codec: call Cambell and after press left 70 times and then call.
For Natasha: Call Master and after press left 28 times and then call
For HAL: Call mey ling and pres right 16 times and then call

**Comment by ShizCalev** [comment]
Duplicate of #15
