### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ethan-BB** [nuggslet/MGSM2Fix#28]
## Issue Summary:
Analog Support broken by 1.5.0 patch

## MGSM2Fix & Game Version Number:
2.1

**Comment by nuggslet** [comment]
On initial inspection, there's not much for M2Fix to do - seems Konami forgot to update the Steam Input configuration to make use of the official support in 1.5.0. This is purely a Steam issue - I would expect consoles to be working fine.

**Comment by MikeChester92** [comment]
The issue has been resolved by Konami.
Personally tested it and now the analogue ones work without the need for the MOD.

https://store.steampowered.com/news/app/2131630/view/5921742839581758119
