### ISSUE TITLE
[Bug]: Issues when using a custom Internal Resolution.

### ISSUE THREAD

**Issue by the-big-cool** [nuggslet/MGSM2Fix#29]
Hello, I'm encountering several issues when using a custom internal resolution. First, whenever I go underwater the game view just gets zoomed in on the top left, there's already an issue open about this but I figured I'd mention it anyways. The other issues I haven't seen mentioned elsewhere though. 

First, during some cutscenes there's a weird semi-transparent overlay of some sort? I think it's just level geometry or something but it's kind of hard to tell and also hard to describe so sorry if this doesn't make any sense, I can provide screenshots if needed. This is my first time playing through the MGS games so I thought it was just a stylistic choice that's in the game at first but I disabled the internal res in the *.ini file and it went away so I guess not. Either way it's very distracting. Also during the cutscene where you first meet Revolver Ocelot, there's a concrete wall or pillar or something blocking him from view of the camera that also isn't there if I disable the internal res option, not sure what that's about or if it's related. Also, it seems like some text just doesn't appear, like the info for save files when saving or loading, they're just blank.

I'm playing on a Steam Deck OLED and running the latest version of both the game and MGSM2Fix. 

It's been like a month since this mod was updated so I hope development on it isn't discontinued, fixing these few bugs would make it practically perfect.

**Comment by ShizCalev** [comment]
> It's been like a month since this mod was updated so I hope development on it isn't discontinued, fixing these few bugs would make it practically perfect.

It's still in development, the creator actively posts updates on the Metal Gear Network discord (almost daily updates.)

**Comment by jellobyte** [comment]
I just realized this was an issue as well. I ran into all the issues you described but the most aggravating issue with it is that among the disappeared text in the game is also the digits on the codec screen. I didn't realize this until needing to call Meryl after the Ocelot fight. Sure enough, once I disabled internal res scaling the digits returned.

**Comment by sauravkumar173** [comment]
Hello, I'm still getting this issue in MGS1. its especially distracting in the cut scenes since it looks like camera is clipping into the walls slightly. Has anyone found a fix for this? It makes playing the game with internal resolution difficult.

**Comment by ShizCalev** [comment]
> Has anyone found a fix for this?

You have to wait for the mod maker to finish making a fix. They post very frequent updates on the discord.

![image](https://github.com/user-attachments/assets/ac695d58-1a8d-426b-ae06-ab787de9d409)
![image](https://github.com/user-attachments/assets/a35e7947-7dc4-432b-bf5d-c837ef31c691)

**Comment by nuggslet** [comment]
Yeah, project is still being worked on - don't worry! Time hasn't been tremendously forthcoming in recent months but I'm chipping away at things and should have more time going forward! Using #15 to track internal resolution issues.
