### ISSUE TITLE
[Bug]: scaled not working MGS1 pixele...

### ISSUE THREAD

**Issue by zerr10** [nuggslet/MGSM2Fix#33]
v.2.0.0 windows 11 pro

RTX 4070 Ti Super Ryzen 9 ZEN 5 4,4ghz

why this not working i put all files on folder game mgs 1 and nothing not scale resolution on full screen

![Bez tytułu](https://github.com/user-attachments/assets/fac6d273-4009-4976-a2fc-f89d48d0dd7a)

**Comment by zerr10** [comment]
;;;;;;;;;; General ;;;;;;;;;;

[External Resolution]
; Enter your chosen resolution.
; You can leave these at 0 if you want your desktop resolution used instead.
Enabled = true
Width = 0
Height = 0
Windowed = false
Borderless = false

[Internal Resolution]
; MGS1 only: Enables render resolution scaling.
; Width is controlled using the in-game settings. Leave the height at 0 to use the external resolution.
Enabled = false
Height = 0
Widescreen = false

[Launcher]
; Skips the warnings / logos on start.
SkipNotice = true
; MGS1 only: Starts the game directly with the previously saved settings and game version.
; You can change those options by going back to the main menu via the pause menu.
StartGame = false

[Patches]
; MGS1 only: Reverts the Master Collection texture swap for Johnny's underpants.
RemoveUnderpants = true
; MGS1 only: Restores the mosaic blur effect on Johnny from original western releases.
EnableMosaic = true
; MGS1 only: Reverts the Master Collection texture swaps for ghost exorcism.
RestoreGhosts = true
; MGS1 only: Reverts the Master Collection texture swaps for medicine items.
RestoreMedicine = true

; MGS1 only: Advanced option, master toggle for *all* RAM patches.
DisableRAM = false
; MGS1 only: Advanced option, master toggle for *all* CD-ROM patches.
DisableCDROM = false

[Game]
; MGS1 only: Enables the in-game developer menu (stage select).
; When enabled, the menu starts up in place of the title screen.
; Selecting 'title' on the menu will load the title screen as normal.
StageSelect = false

;;;;;;;;;; Developer ;;;;;;;;;;

[Squirrel Debugger]
; Injects SQDbg into the Squirrel VM.
; Advanced option, leave it disabled if you just want to play the game.
Enabled = false
Port = 27615
AutoUpdate = true
Exclusive = false

[Tracing]
; Enables tracing of Squirrel scripts to the log file.
Level = 0
; Enables tracing of Squirrel native calls to the log file.
NativeLevel = 0
; Enables tracing of spammy emulator hooks to the log file.
EmulatorLevel = 0

**Comment by zerr10** [comment]
![Uploading Bez tytułu 2.jpg…]()

**Comment by zerr10** [comment]
next screen option i dont know not woking pls help
![Bez tytułu 2](https://github.com/user-attachments/assets/6426344a-b81e-42ef-906d-b81cfb57609a)

**Comment by zerr10** [comment]
i see scale only menu but game not

**Comment by zerr10** [comment]
is version 2.0.0 will anyone help?

**Comment by forerunnerchief** [comment]
@zerr10 Not sure if you already figured it out, but you need to enable Internal Resolution.

```ini
[Internal Resolution]
; MGS1 only: Enables render resolution scaling.
; Width is controlled using the in-game settings. Leave the height at 0 to use the external resolution.
Enabled = true
```

If it doesn't set it to your native resolution automatically, try setting your resolution manually under `External Resolution`.
