### ISSUE TITLE
[Bug]: Windows cannot find 'WINEDLLOVERRIDES="d3d11=n,b" %command%' error when trying to boot up the game

### ISSUE THREAD

**Issue by lordwahu** [nuggslet/MGSM2Fix#34]
## Issue Summary:

While playing on Windows 11, I have followed the install instructions provided in the readme. However, setting the launch properties as instructed triggered the error. I have been unable to launch the game with the changed settings, and most importantly for me, been unable to use the Ketchup mod launcher

## MGSM2Fix & Game Version Number:
MGSM2Fix v2.2

## Log Files:
[MGSM2Fix.log](https://github.com/user-attachments/files/18222101/MGSM2Fix.log)

## Reproduction:

Attempted to run the program numerous times, trying a few other launch options I know for windows

![image](https://github.com/user-attachments/assets/e4be62ef-e063-4e42-bac4-8d0c4e674276)

**Comment by nuggslet** [comment]
Looks like you have a Steam launch options override intended for Steam Deck enabled. Clearing the launch options on the game properties in Steam should fix it.
